const express = require("express");
const verifyAdminAccessToken = require("../middlewares/verifyAdminAccessToken");
const router = express.Router();
const adminController = require("../controllers").adminController;

router.post("/login", adminController.login);
router.post("/signup", adminController.signUp);
router.get("/details", verifyAdminAccessToken, adminController.getAdminDetails);
router.get(
  "/patient/details/:patientId",
  verifyAdminAccessToken,
  adminController.getPatientDetails,
);
router.post(
  "/hospital/create",
  // verifyAdminAccessToken,
  adminController.createHospitals,
);
router.get(
  "/feedback/list",
  verifyAdminAccessToken,
  adminController.getFeedbackList,
);
router.post(
  "/hospital/doctor/create",
  verifyAdminAccessToken,
  adminController.createDoctors,
);
router.patch(
  "/hospital/user/profile/update",
  verifyAdminAccessToken,
  adminController.updateUserProfileDetails,
);
router.post(
  "/hospital/admin/create",
  verifyAdminAccessToken,
  adminController.createAdmin,
);
router.get(
  "/hospital/admin/list",
  verifyAdminAccessToken,
  adminController.getAdminList,
);
router.get(
  "/hospital/doctor/list",
  verifyAdminAccessToken,
  adminController.getDoctorsList,
);
router.get(
  "/hospital/doctor/details/:doctorId",
  verifyAdminAccessToken,
  adminController.getDoctorDetails,
);
router.get(
  "/hospital/admin/details/:userId",
  verifyAdminAccessToken,
  adminController.getUserDetails,
);
router.patch(
  "/hospital/admin/update/:userId",
  verifyAdminAccessToken,
  adminController.updateAdminDetails,
);
router.patch(
  "/hospital/doctor/update/:doctorId",
  verifyAdminAccessToken,
  adminController.updateDoctorDetails,
);
router.post(
  "/hospital/weekdays/create",
  verifyAdminAccessToken,
  adminController.createWeekDays,
);
router.get(
  "/hospital/weekdays/list",
  verifyAdminAccessToken,
  adminController.getWeekDaysList,
);
router.post(
  "/hospital/slots/create",
  verifyAdminAccessToken,
  adminController.createSlots,
);
router.post(
  "/hospital/slots/create/single",
  verifyAdminAccessToken,
  adminController.createSlotSingle,
);
router.patch(
  "/hospital/slots/edit/:slotId",
  verifyAdminAccessToken,
  adminController.editSlot,
);
router.delete(
  "/hospital/slots/delete/:slotId",
  verifyAdminAccessToken,
  adminController.deleteSlot,
);
router.get(
  "/hospital/slots/admin/list",
  verifyAdminAccessToken,
  adminController.getSlotList,
);
router.get(
  "/hospital/slots/list",
  verifyAdminAccessToken,
  adminController.getSlotListForDoctors,
);
router.post(
  "/hospital/doctorslot/create",
  verifyAdminAccessToken,
  adminController.createDoctorsSlot,
);
router.post(
  "/hospital/ailment/create",
  verifyAdminAccessToken,
  adminController.createAilment,
);
router.patch(
  "/hospital/ailment/update/:ailmentId",
  verifyAdminAccessToken,
  adminController.updateAilment,
);
router.get(
  "/hospital/ailment/list",
  verifyAdminAccessToken,
  adminController.getAlimentList,
);
router.delete(
  "/hospital/ailment/delete/:ailmentId",
  verifyAdminAccessToken,
  adminController.deleteAilment,
);
router.post(
  "/hospital/doctype/create",
  verifyAdminAccessToken,
  adminController.createdocumentType,
);
router.get(
  "/hospital/appointment/list",
  verifyAdminAccessToken,
  adminController.getAppointmentList,
);
router.get(
  "/hospital/appointment/details/:appointmentId",
  verifyAdminAccessToken,
  adminController.getAppointmentDetails,
);
router.post(
  "/hospital/appointment/update/status",
  verifyAdminAccessToken,
  adminController.updateAppointmentStatus,
);
router.post(
  "/hospital/medication/create",
  verifyAdminAccessToken,
  adminController.createMedication,
);
router.get(
  "/hospital/medication/list",
  verifyAdminAccessToken,
  adminController.getMedicationList,
);
router.patch(
  "/hospital/medication/update/:medicationId",
  verifyAdminAccessToken,
  adminController.updateMedicationDetails,
);
router.delete(
  "/hospital/medication/delete/:medicationId",
  verifyAdminAccessToken,
  adminController.deleteMedication,
);
router.get(
  "/hospital/patients/list",
  verifyAdminAccessToken,
  adminController.getPatientList,
);
router.get(
  "/dashboard/overview/metrics",
  verifyAdminAccessToken,
  adminController.getDashboardOverview,
);
router.get(
  "/dashboard/overview/metrics/today",
  verifyAdminAccessToken,
  adminController.getDashboardOverviewToday,
);
module.exports = router;
